name: Docker Image CI Latest

on:
  push:
    branches: [ "main" ]
  schedule:
  - cron: "0 2 1 1,4,7,10 *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/auto-update-esphome

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Save state
        run: |
          version=`cat ./VERSION` 
          echo "version=$version" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

          push: ${{ github.event_name != 'pull_request' }}

          tags: victordrijkoningen/auto-update-esphome:latest, victordrijkoningen/auto-update-esphome:v${{env.version}}-${{date +'%Y-%m'}}

          annotations: ${{ steps.meta.outputs.annotations }}

          provenance: true

          sbom: true
          
                